[package]
name = "solana-budget-program"
version = "1.6.14"
description = "Solana Budget program"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-budget-program"
edition = "2018"

[dependencies]
bincode = "1.3.1"
chrono = { version = "0.4.11", features = ["serde"] }
log = "0.4.11"
num-derive = "0.3"
num-traits = "0.2"
serde = "1.0.122"
serde_derive = "1.0.103"
solana-sdk = { path = "../../sdk", version = "=1.9.29" }
thiserror = "1.0"

[dev-dependencies]
solana-runtime = { path = "../../runtime", version = "=1.9.29" }

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
