[package]
name = "solana-entry"
version = "1.9.29"
description = "Solana Entry"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-poh"
edition = "2021"

[dependencies]
dlopen = "0.1.8"
dlopen_derive = "0.1.4"
log = "0.4.11"
rand = "0.7.0"
rayon = "1.5.1"
serde = "1.0.130"
solana-measure = { path = "../measure", version = "=1.9.29" }
solana-merkle-tree = { path = "../merkle-tree", version = "=1.9.29" }
solana-metrics = { path = "../metrics", version = "=1.9.29" }
solana-perf = { path = "../perf", version = "=1.9.29" }
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "=1.9.29" }
solana-sdk = { path = "../sdk", version = "=1.9.29" }
bincode = "1.3.3"

[dev-dependencies]
matches = "0.1.9"
solana-logger = { path = "../logger", version = "=1.9.29" }

[lib]
crate-type = ["lib"]
name = "solana_entry"

[[bench]]
name = "entry_sigverify"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
