[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-poh-bench"
version = "1.9.29"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-poh-bench"
publish = false

[dependencies]
clap = "2.33.1"
log = "0.4.14"
rand = "0.7.0"
rayon = "1.5.1"
solana-logger = { path = "../logger", version = "=1.9.29" }
solana-entry = { path = "../entry", version = "=1.9.29" }
solana-sdk = { path = "../sdk", version = "=1.9.29" }
solana-measure = { path = "../measure", version = "=1.9.29" }
solana-version = { path = "../version", version = "=0.6.3" }
solana-perf = { path = "../perf", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
