[package]
name = "solana-rayon-threadlimit"
version = "1.9.29"
description = "solana-rayon-threadlimit"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-rayon-threadlimit"
readme = "../README.md"
repository = "https://github.com/solana-labs/solana"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
license = "Apache-2.0"
edition = "2021"

[dependencies]
num_cpus = "1.13.0"
lazy_static = "1.4.0"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
