[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2018"
name = "solana-scripts"
description = "Blockchain, Rebuilt for Scale"
version = "1.6.14"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
csv = "1.1"
serde = { version = "1.0.122", features = ["derive"] }

[[bin]]
name = "solana-csv-to-validator-infos"
path = "src/csv_to_validator_infos.rs"


[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
