[package]
name = "solana-rpc-test"
version = "1.9.29"
description = "Solana RPC Test"
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
documentation = "https://docs.rs/solana-rpc-test"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bs58 = "0.4.0"
jsonrpc-core = "18.0.0"
jsonrpc-core-client = { version = "18.0.0", features = ["ipc", "ws"] }
log = "0.4.11"
reqwest = { version = "0.11.5", default-features = false, features = ["blocking", "rustls-tls", "json"] }
serde = "1.0.130"
serde_json = "1.0.72"
solana-account-decoder = { path = "../account-decoder", version = "=1.9.29" }
solana-client = { path = "../client", version = "=1.9.29" }
solana-rpc = { path = "../rpc", version = "=1.9.29" }
solana-sdk = { path = "../sdk", version = "=1.9.29" }
solana-streamer = { path = "../streamer", version = "=1.9.29" }
solana-test-validator = { path = "../test-validator", version = "=1.9.29" }
solana-transaction-status = { path = "../transaction-status", version = "=1.9.29" }
tokio = { version = "1.14.1", features = ["full"] }
solana-evm-loader-program = { path = "../evm-utils/programs/evm_loader" }
evm-rpc = { path = "../evm-utils/evm-rpc" }
evm-state = { path = "../evm-utils/evm-state" }
hex = "0.4"
primitive-types = "0.11.0"

[dev-dependencies]
solana-logger = { path = "../logger", version = "=1.9.29" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
