[package]
authors = ["Solana Maintainers <maintainers@solana.foundation>"]
edition = "2021"
name = "solana-store-tool"
description = "Tool to inspect append vecs"
version = "1.9.29"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
log = { version = "0.4.14" }
solana-logger = { path = "../../logger", version = "=1.9.29" }
solana-version = { path = "../../version", version = "=0.6.3" }
solana-runtime = { path = "..", version = "=1.9.29" }
clap = "2.33.1"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
