name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - devnet
      - 'build/**'

jobs:
  docker-build-push:
    name: Build and push
    runs-on: build-dedicated
    outputs:
      repository: ${{ steps.build.outputs.repository }}
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          registry: ${{ secrets.REGISTRY_HOST }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
          push: true
          tags: ${{ secrets.REGISTRY_HOST }}/chui/chui-solana:${{github.sha}}
